services:
  - type: web
    name: n8n
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_HOST
        value: https://n8n-on-render.onrender.com
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: ismael
      - key: N8N_BASIC_AUTH_PASSWORD
        value: ClaveSegura123
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_DATABASE
        value: n8n
      - key: DB_POSTGRESDB_USERNAME
        value: n8n
      - key: DB_POSTGRESDB_PASSWORD
        generateValue: true
      - key: DB_POSTGRESDB_HOST
        fromService:
          type: database
          name: postgres
          property: host
      - key: DB_POSTGRESDB_PORT
        fromService:
          type: database
          name: postgres
          property: port

databases:
  - name: postgres
    plan: free
    databaseName: n8n
    user: n8n
